---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: goof
  name: goof
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goof
  template:
    metadata:
      labels:
        app: goof
    spec:
      containers:
      - image: ${DOCKER_ACCOUNT}/java-goof:latest
        imagePullPolicy: Always
        name: java-goof
        livenessProbe: true
        resources:
          requests:
              memory: "64Mi"
              cpu: "250m"
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
          runAsUser: 10000000
          readOnlyRootFilesystem : true
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: goof
  name: goof
spec:
  type: LoadBalancer
  loadBalancerSourceRanges: "192.168.1.0/24"
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: goof
